spring:
  application:
    name: resource

server:
  port: 9000

###################################
# EUREKA
###################################
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
#
#feign.hystrix.enabled: false

###################################
# SECURITY
###################################
#security:
#  basic.enabled: false
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:8080/user
#      jwt:
#        keyValue: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhvMhw3FBuwzN6gX6kagH0Z6abLoeRDns+m53SrpIEndNHv4m0Olj9Hp7sm1OiYz0VYlxRybhwgY8DFR6C3O7imEK02lAt/rjhEUjy2kIzeHqojJnuYgbGy0BRxMm4GFPiaQfBF9/Hn7x/JhZSWRls/dAQlRYGHi08jj6AwMf1yZbPS6FvuOJOBfLT8Opn4sp7vScVbTFt5/UZyyKqq6vALizQbBVrhGtsPxV6cY0fiPLBwpw/vYMaWzhLP+lNb/EuWMFLagg9uxTj2y5KKHvdrfOMNTJqABoSDIBhUPdao9DBCjDtVJ2V3fSIiGLR5wt287eA7oYfjiPk2N+eA+gawIDAQAB
#          -----END PUBLIC KEY-----

###################################
# DATABASE
###################################
spring.datasource.url: jdbc:postgresql://localhost:5432/resource_service
spring.datasource.username: postgres
spring.datasource.password: root
spring.datasource.platform: POSTGRESQL

spring.jpa.hibernate.ddl-auto: update


###################################
# LOGGING
###################################
#logging.level.project.user.CursoClient: DEBUG
#logging.level.org.springframework.security: DEBUG
