# Define the port where the Widget Foundry server would be running
server:
  port: 9001
  contextPath: /curso

logging.level.org.springframework.security: DEBUG


# Disable spring basic authentication security
security:
  basic.enabled: false
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhvMhw3FBuwzN6gX6kagH0Z6abLoeRDns+m53SrpIEndNHv4m0Olj9Hp7sm1OiYz0VYlxRybhwgY8DFR6C3O7imEK02lAt/rjhEUjy2kIzeHqojJnuYgbGy0BRxMm4GFPiaQfBF9/Hn7x/JhZSWRls/dAQlRYGHi08jj6AwMf1yZbPS6FvuOJOBfLT8Opn4sp7vScVbTFt5/UZyyKqq6vALizQbBVrhGtsPxV6cY0fiPLBwpw/vYMaWzhLP+lNb/EuWMFLagg9uxTj2y5KKHvdrfOMNTJqABoSDIBhUPdao9DBCjDtVJ2V3fSIiGLR5wt287eA7oYfjiPk2N+eA+gawIDAQAB
          -----END PUBLIC KEY-----
      #id: openid
      #serviceId: ${PREFIX:}resource

feign.hystrix.enabled: false
logging.level.project.user.CursoClient: DEBUG